# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180116_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='courses',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
