# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='实事求是', max_length=20, verbose_name='标签'),
        ),
    ]
