# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-21 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='you_can_learn',
            field=models.CharField(default='', max_length=300, verbose_name='你能学到的技能'),
        ),
        migrations.AddField(
            model_name='course',
            name='you_need_to_know',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
    ]
