# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180121_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='课程是否轮播'),
        ),
    ]
